language: python
python:
  - "3.x"
install:
  - pip install markdown
script:
  - python3 resume.py
deploy:
  provider: releases
  api_key: 
    secure: ${GH_TOKEN}
  file: 
  - resume.pdf 
  - resume_en.pdf
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

