language: latex
script:
  - ./laton -c xelatex -d tex.buaadml.info -g resume.tex
before_deploy:
  - curl -L https://raw.githubusercontent.com/aslushnikov/latex-online/master/util/latexonline > laton && chmod 755 laton
deploy:
  provider: releases
  api_key: 
    secure: ${GH_TOKEN}
  file: resume.pdf
  skip_cleanup: true
  on:
    tags: false
